spring:
  # JPA
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        use_sql_comments: true
        show_sql: true
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # application-auth
  profiles:
    include: auth

# log level setting
logging:
  level:
    root: info
    com:
      jjplanet: debug